kind: pipeline
type: docker
name: CI Pipeline

trigger:
  branch:
    - main
  event:
    - push
    - tag
  ref:
    - refs/tags/v[0-9]+.[0-9]+.[0-9]+
    - refs/tags/v[0-9]+.[0-9]+.[0-9]+-avaxia*
    - refs/tags/v[0-9]+.[0-9]+.[0-9]+-rc*

steps:

# -------------------------
# SONARQUBE
# -------------------------
- name: sonarqube
  image: sonarsource/sonar-scanner-cli
  environment:
    SONAR_TOKEN:
      from_secret: SONAR_TOKEN
    SONAR_HOST_URL:
      from_secret: SONAR_HOST_URL
  commands:
    - sonar-scanner

# -------------------------
# SET ENVIRONMENT
# -------------------------
- name: set-environment
  image: node:20
  depends_on:
    - sonarqube
  environment:
    # All values are secrets now
    GHA_RELEASE_REPO_DEV:
      from_secret: GHA_RELEASE_REPO_DEV
    GHA_RELEASE_REPO_STG:
      from_secret: GHA_RELEASE_REPO_STG
    GHA_RELEASE_REPO_PRD:
      from_secret: GHA_RELEASE_REPO_PRD

    GHA_HELM_RELEASE_REPO:
      from_secret: GHA_HELM_RELEASE_REPO

    GHA_HELM_PROJECT_DEV:
      from_secret: GHA_HELM_PROJECT_DEV
    GHA_HELM_PROJECT_STG:
      from_secret: GHA_HELM_PROJECT_STG
    GHA_HELM_PROJECT_PRD:
      from_secret: GHA_HELM_PROJECT_PRD

    GHA_PROJECT_REPO_DEV:
      from_secret: GHA_PROJECT_REPO_DEV
    GHA_PROJECT_REPO_STG:
      from_secret: GHA_PROJECT_REPO_STG
    GHA_PROJECT_REPO_PRD:
      from_secret: GHA_PROJECT_REPO_PRD

    GHA_REGISTRY_NAME_DEV:
      from_secret: GHA_REGISTRY_NAME_DEV
    GHA_REGISTRY_NAME_STG:
      from_secret: GHA_REGISTRY_NAME_STG
    GHA_REGISTRY_NAME_PRD:
      from_secret: GHA_REGISTRY_NAME_PRD

    GHA_REGISTRY_DOMAIN:
      from_secret: GHA_REGISTRY_DOMAIN

    GHA_IMAGE_NAME:
      from_secret: GHA_IMAGE_NAME

    GHA_HELM_VALUES_SECTION_NAME:
      from_secret: GHA_HELM_VALUES_SECTION_NAME

    ACR_USERNAME_DEV:
      from_secret: ACR_USERNAME_DEV
    ACR_PASSWORD_DEV:
      from_secret: ACR_PASSWORD_DEV

    ACR_USERNAME_STG:
      from_secret: ACR_USERNAME_STG
    ACR_PASSWORD_STG:
      from_secret: ACR_PASSWORD_STG

    ACR_USERNAME_PRD:
      from_secret: ACR_USERNAME_PRD
    ACR_PASSWORD_PRD:
      from_secret: ACR_PASSWORD_PRD

  commands:
    - |
      node <<'EOF'
      const fs = require('fs')

      const isDev = process.env.DRONE_BRANCH === 'dev'
      const isStg = process.env.DRONE_TAG && process.env.DRONE_TAG.includes('-rc')
      const isPrd = process.env.DRONE_TAG && process.env.DRONE_TAG.includes('-avaxia')

      let env = {}

      if (isDev) {
        env.environment = "development"
        env.environment_display = "Dev"
        env.release_repo = process.env.GHA_RELEASE_REPO_DEV
        env.helm_release_repo = process.env.GHA_HELM_RELEASE_REPO
        env.kustomize_folder = process.env.GHA_PROJECT_REPO_DEV
        env.helm_folder = process.env.GHA_HELM_PROJECT_DEV
        env.acr_name = `${process.env.GHA_REGISTRY_NAME_DEV}.${process.env.GHA_REGISTRY_DOMAIN}`
        env.acr_username = process.env.ACR_USERNAME_DEV
        env.acr_password = process.env.ACR_PASSWORD_DEV
        env.docker_tag = `${env.acr_name}/${process.env.GHA_IMAGE_NAME}:${process.env.DRONE_COMMIT_SHA}`
        env.helm_tag = process.env.DRONE_COMMIT_SHA
      } else if (isStg) {
        env.environment = "staging"
        env.environment_display = "Staging"
        env.release_repo = process.env.GHA_RELEASE_REPO_STG
        env.kustomize_folder = process.env.GHA_PROJECT_REPO_STG
        env.helm_folder = process.env.GHA_HELM_PROJECT_STG
        env.acr_name = `${process.env.GHA_REGISTRY_NAME_STG}.${process.env.GHA_REGISTRY_DOMAIN}`
        env.acr_username = process.env.ACR_USERNAME_STG
        env.acr_password = process.env.ACR_PASSWORD_STG
        env.docker_tag = `${env.acr_name}/${process.env.GHA_IMAGE_NAME}:${process.env.DRONE_TAG}`
        env.helm_tag = process.env.DRONE_TAG
      } else if (isPrd) {
        env.environment = "production"
        env.environment_display = "Production"
        env.release_repo = process.env.GHA_RELEASE_REPO_PRD
        env.kustomize_folder = process.env.GHA_PROJECT_REPO_PRD
        env.helm_folder = process.env.GHA_HELM_PROJECT_PRD
        env.acr_name = `${process.env.GHA_REGISTRY_NAME_PRD}.${process.env.GHA_REGISTRY_DOMAIN}`
        env.acr_username = process.env.ACR_USERNAME_PRD
        env.acr_password = process.env.ACR_PASSWORD_PRD
        env.docker_tag = `${env.acr_name}/${process.env.GHA_IMAGE_NAME}:${process.env.DRONE_TAG}`
        env.helm_tag = process.env.DRONE_TAG
      } else {
        console.error("Unknown environment")
        process.exit(1)
      }

      fs.writeFileSync('.drone-env', Object.entries(env).map(e => e.join('=')).join('\n'))
      fs.writeFileSync('.env', fs.readFileSync('.drone-env'))
      EOF

# -------------------------
# DOCKER BUILD & PUSH
# -------------------------
- name: docker-build-push
  image: docker:27
  depends_on:
    - set-environment
  privileged: true
  commands:
    - source .drone-env
    - docker login $acr_name -u $acr_username -p $acr_password
    - docker build -t $docker_tag $(for i in `cat .env`; do echo --build-arg $i; done) .
    - docker push $docker_tag

# -------------------------
# KUSTOMIZE RELEASE
# -------------------------
- name: kustomize-release
  image: alpine/git
  depends_on:
    - docker-build-push
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUBTOKEN
  commands:
    - source .drone-env
    - git clone https://$GITHUB_TOKEN@github.com/$release_repo.git repo
    - cd repo/$kustomize_folder
    - kustomize edit set image $docker_tag
    - git config user.name "avaxiagroup"
    - git config user.email "devops-team@avaxia-group.com"
    - git commit -am "Pushing to $environment $docker_tag"
    - git push
