kind: pipeline
type: docker
name: test

steps:
  - name: hello
    image: alpine:latest
    commands:
      - echo "Drone CI is working!"
      - echo "Branch: ${DRONE_BRANCH}"
      - echo "Commit: ${DRONE_COMMIT_SHA}"