kind: pipeline
type: kubernetes
name: ci-pipeline
 
trigger:
  branch:
    - dev
  # event:
  #   - push
  #   - tag
 
steps:
 
# -------------------------
# Set Environment & .env
# -------------------------
- name: set-env
  image: alpine:3.19
  environment:
    DRONE_BRANCH: ${DRONE_BRANCH}
    DRONE_TAG: ${DRONE_TAG}
    DRONE_COMMIT_SHA: ${DRONE_COMMIT_SHA}
 
    ACR_LOGIN_SERVER:
      from_secret: ACR_LOGIN_SERVER
    ACR_IMAGE_NAME:
      from_secret: ACR_IMAGE_NAME
 
    # DEV
    GHA_RELEASE_REPO_DEV:
      from_secret: GHA_RELEASE_REPO_DEV
    GHA_PROJECT_REPO_DEV:
      from_secret: GHA_PROJECT_REPO_DEV
 
    # STG
    GHA_RELEASE_REPO_STG:
      from_secret: GHA_RELEASE_REPO_STG
    GHA_PROJECT_REPO_STG:
      from_secret: GHA_PROJECT_REPO_STG
 
    # PRD
    GHA_RELEASE_REPO_PRD:
      from_secret: GHA_RELEASE_REPO_PRD
    GHA_PROJECT_REPO_PRD:
      from_secret: GHA_PROJECT_REPO_PRD
 
  commands:
    - |
      set -e
 
      if [ "$DRONE_BRANCH" = "dev" ]; then
        ENV=development
        TAG=$DRONE_COMMIT_SHA
        RELEASE_REPO=$GHA_RELEASE_REPO_DEV
        KUSTOMIZE_FOLDER=$GHA_PROJECT_REPO_DEV
 
      elif echo "$DRONE_TAG" | grep -q -- "-rc"; then
        ENV=staging
        TAG=$DRONE_TAG
        RELEASE_REPO=$GHA_RELEASE_REPO_STG
        KUSTOMIZE_FOLDER=$GHA_PROJECT_REPO_STG
 
      elif echo "$DRONE_TAG" | grep -q -- "-avaxia"; then
        ENV=production
        TAG=$DRONE_TAG
        RELEASE_REPO=$GHA_RELEASE_REPO_PRD
        KUSTOMIZE_FOLDER=$GHA_PROJECT_REPO_PRD
 
      else
        echo "Unknown environment"
        exit 1
      fi
 
      IMAGE="$ACR_LOGIN_SERVER/$ACR_IMAGE_NAME:$TAG"
 
      echo "ENV=$ENV" > .env
      echo "IMAGE=$IMAGE" >> .env
      echo "RELEASE_REPO=$RELEASE_REPO" >> .env
      echo "KUSTOMIZE_FOLDER=$KUSTOMIZE_FOLDER" >> .env
 
      cat .env
 
# -------------------------------------------------
# Build & Push to Azure Container Registry (Kaniko)
# -------------------------------------------------
- name: build-and-push-acr
  image: gcr.io/kaniko-project/executor:debug
  environment:
    ACR_LOGIN_SERVER:
      from_secret: ACR_LOGIN_SERVER
    ACR_USERNAME:
      from_secret: ACR_USERNAME
    ACR_PASSWORD:
      from_secret: ACR_PASSWORD
 
  commands:
    - |
      set -e
 
      mkdir -p /kaniko/.docker
 
      cat > /kaniko/.docker/config.json <<EOF
      {
        "auths": {
          "https://$ACR_LOGIN_SERVER": {
            "username": "$ACR_USERNAME",
            "password": "$ACR_PASSWORD"
          }
        }
      }
      EOF
 
      . .env
 
      /kaniko/executor \
        --context . \
        --dockerfile Dockerfile \
        --destination "$IMAGE" \
        --cache=true \
        --cache-repo "$(echo $IMAGE | cut -d: -f1)-cache"
# -------------------------
# Production Approval (TAG only)
# -------------------------
- name: request-approval
  image: python:3.11-alpine
  when:
    event:
      - tag
  environment:
    EMAIL_PASSWORD:
      from_secret: EMAIL_PASSWORD
  commands:
    - python3 application-scripts/Pipelines/approval/approval-oneperson.py
 
# -------------------------
# Kustomize GitOps Release
# -------------------------
- name: kustomize-release
  image: alpine/k8s:1.30.1
  environment:
    GITHUBTOKEN:
      from_secret: GITHUBTOKEN
  commands:
    - |
      set -e
      . .env
 
      git clone https://$GITHUBTOKEN@github.com/$RELEASE_REPO.git
      cd $KUSTOMIZE_FOLDER
 
      kustomize edit set image app=$IMAGE
 
      git config user.name "drone-ci"
      git config user.email "devops@avaxia-group.com"
 
      git commit -am "Release $IMAGE"
      git push