kind: pipeline
type: kubernetes
name: ci-pipeline

trigger:
  branch:
    - dev
  # event:
  #   - push
  #   - tag

steps:

# SonarQube
# - name: sonarqube
#   image: sonarsource/sonar-scanner-cli
#   environment:
#     SONAR_TOKEN:
#       from_secret: SONAR_TOKEN
#     SONAR_HOST_URL:
#       from_secret: SONAR_HOST_URL
#   commands:
#     - sonar-scanner

# Set environment (DEV / STG / PRD) -> writes .outputs
- name: set-env
  image: node:18
  environment:
    DRONE_BRANCH: ${DRONE_BRANCH}
    DRONE_TAG: ${DRONE_TAG}
    DRONE_COMMIT_SHA: ${DRONE_COMMIT_SHA}

    DRONE_IMAGE_NAME:
      from_secret: DRONE_IMAGE_NAME
    DRONE_REGISTRY_DOMAIN:
      from_secret: DRONE_REGISTRY_DOMAIN

    DRONE_RELEASE_REPO_DEV:
      from_secret: DRONE_RELEASE_REPO_DEV
    DRONE_PROJECT_REPO_DEV:
      from_secret: DRONE_PROJECT_REPO_DEV
    DRONE_HELM_PROJECT_DEV:
      from_secret: DRONE_HELM_PROJECT_DEV
    DRONE_REGISTRY_NAME_DEV:
      from_secret: DRONE_REGISTRY_NAME_DEV
    ACR_USERNAME_DEV:
      from_secret: ACR_USERNAME_DEV
    ACR_PASSWORD_DEV:
      from_secret: ACR_PASSWORD_DEV

    DRONE_RELEASE_REPO_STG:
      from_secret: DRONE_RELEASE_REPO_STG
    DRONE_PROJECT_REPO_STG:
      from_secret: DRONE_PROJECT_REPO_STG
    DRONE_HELM_PROJECT_STG:
      from_secret: DRONE_HELM_PROJECT_STG
    DRONE_REGISTRY_NAME_STG:
      from_secret: DRONE_REGISTRY_NAME_STG
    ACR_USERNAME_STG:
      from_secret: ACR_USERNAME_STG
    ACR_PASSWORD_STG:
      from_secret: ACR_PASSWORD_STG

    DRONE_RELEASE_REPO_PRD:
      from_secret: DRONE_RELEASE_REPO_PRD
    DRONE_PROJECT_REPO_PRD:
      from_secret: DRONE_PROJECT_REPO_PRD
    DRONE_HELM_PROJECT_PRD:
      from_secret: DRONE_HELM_PROJECT_PRD
    DRONE_REGISTRY_NAME_PRD:
      from_secret: DRONE_REGISTRY_NAME_PRD
    ACR_USERNAME_PRD:
      from_secret: ACR_USERNAME_PRD
    ACR_PASSWORD_PRD:
      from_secret: ACR_PASSWORD_PRD

  commands:
  - |-
      
        cat <<'NODE' | node
        const fs = require('fs');

        const env = process.env;
        const outputs = {};
        const NL = String.fromCharCode(10);

        function req(k) {
          const v = env[k];
          if (!v) {
            console.error('Missing env var: ' + k);
            process.exit(1);
          }
          return v;
        }

        if (env.DRONE_BRANCH === 'dev') {
          outputs.environment = 'development';
          outputs.environment_display = 'Dev';

          outputs.release_repo = req('DRONE_RELEASE_REPO_DEV');
          outputs.kustomize_folder = req('DRONE_PROJECT_REPO_DEV');

          outputs.helm_folder = req('DRONE_HELM_PROJECT_DEV');
          outputs.helm_release_repo = req('DRONE_RELEASE_REPO_DEV');
          outputs.helm_values_section_name = 'dev';

          outputs.acr_name = req('ACR_USERNAME_DEV') + '.' + req('DRONE_REGISTRY_DOMAIN');
          outputs.acr_username = req('ACR_USERNAME_DEV');
          outputs.acr_password = req('ACR_PASSWORD_DEV');

          outputs.docker_tag = outputs.acr_name + '/' + req('DRONE_IMAGE_NAME') + ':' + req('DRONE_COMMIT_SHA');
          outputs.helm_tag = req('DRONE_COMMIT_SHA');

        } else if (env.DRONE_TAG && env.DRONE_TAG.includes('-rc')) {
          outputs.environment = 'staging';
          outputs.environment_display = 'Staging';

          outputs.release_repo = req('DRONE_RELEASE_REPO_STG');
          outputs.kustomize_folder = req('DRONE_PROJECT_REPO_STG');

          outputs.helm_folder = req('DRONE_HELM_PROJECT_STG');
          outputs.helm_release_repo = req('DRONE_RELEASE_REPO_STG');
          outputs.helm_values_section_name = 'staging';

          outputs.acr_name = req('DRONE_REGISTRY_NAME_STG') + '.' + req('DRONE_REGISTRY_DOMAIN');
          outputs.acr_username = req('ACR_USERNAME_STG');
          outputs.acr_password = req('ACR_PASSWORD_STG');

          outputs.docker_tag = outputs.acr_name + '/' + req('DRONE_IMAGE_NAME') + ':' + req('DRONE_TAG');
          outputs.helm_tag = req('DRONE_TAG');

        } else if (env.DRONE_TAG && env.DRONE_TAG.includes('-avaxia')) {
          outputs.environment = 'production';
          outputs.environment_display = 'Production';

          outputs.release_repo = req('DRONE_RELEASE_REPO_PRD');
          outputs.kustomize_folder = req('DRONE_PROJECT_REPO_PRD');

          outputs.helm_folder = req('DRONE_HELM_PROJECT_PRD');
          outputs.helm_release_repo = req('DRONE_RELEASE_REPO_PRD');
          outputs.helm_values_section_name = 'production';

          outputs.acr_name = req('DRONE_REGISTRY_NAME_PRD') + '.' + req('DRONE_REGISTRY_DOMAIN');
          outputs.acr_username = req('ACR_USERNAME_PRD');
          outputs.acr_password = req('ACR_PASSWORD_PRD');

          outputs.docker_tag = outputs.acr_name + '/' + req('DRONE_IMAGE_NAME') + ':' + req('DRONE_TAG');
          outputs.helm_tag = req('DRONE_TAG');

        } else {
          console.error('Unknown environment. Expected: branch dev OR tag with -rc OR tag with -avaxia');
          process.exit(1);
        }

        fs.writeFileSync(
          '.outputs',
          Object.entries(outputs).map(([k, v]) => k + '=' + v).join(NL)
        );

        console.log('=== .outputs ===');
        console.log(fs.readFileSync('.outputs', 'utf8'));
        NODE


# Build & Push Docker (Kaniko)
- name: docker-build-push
  image: gcr.io/kaniko-project/executor:debug
  environment:
    DOCKER_CONFIG: /kaniko/.docker
  commands:
    - export $(cat .outputs | xargs)
    - mkdir -p /kaniko/.docker
    - |-
      cat <<EOF > /kaniko/.docker/config.json
      {
        "auths": {
          "$acr_name": {
            "username": "$acr_username",
            "password": "$acr_password"
          }
        }
      }
      EOF
    - /kaniko/executor --context . --dockerfile Dockerfile --destination "$docker_tag"

# REQUEST DEPLOYMENT APPROVAL (TAGS ONLY)
- name: deployment-approval
  image: python:3.11
  when:
    event:
      - tag
  environment:
    EMAIL_USERNAME:
      from_secret: EMAIL_USERNAME
    EMAIL_PASSWORD:
      from_secret: EMAIL_PASSWORD
    APPROVERS:
      from_secret: APPROVERS
    APPROVERS_NAME:
      from_secret: APPROVERS_NAME
    PROJECT_ID:
      from_secret: PROJECT_ID
  commands:
    - pip install imapclient
    - python application-scripts/Pipelines/approval/approval-oneperson.py

# Helm Release (update values.yaml tag) - working
# Helm Release (update values.yaml tag) - robust
- name: helm-release
  image: alpine:3.20
  environment:
    DEPLOYMENT_TOKEN:
      from_secret: DEPLOYMENT_TOKEN
  commands:
    - apk add --no-cache git sed
    - export $(cat .outputs | xargs)

    - |-
      set -e

      echo "helm_release_repo=$helm_release_repo"
      echo "helm_folder=$helm_folder"
      echo "helm_values_section_name=$helm_values_section_name"
      echo "helm_tag=$helm_tag"

      git clone "https://x-access-token:${DEPLOYMENT_TOKEN}@github.com/${helm_release_repo}.git" repo

      cd repo

      echo "== repo root =="
      ls -la

      echo "== helm folder (${helm_folder}) =="
      if [ ! -d "${helm_folder}" ]; then
        echo "Folder not found: ${helm_folder}"
        exit 1
      fi
      ls -la "${helm_folder}"

      VALUES_FILE="${helm_folder}/values.yaml"
      if [ ! -f "${VALUES_FILE}" ]; then
        echo "values.yaml not found at ${VALUES_FILE}"
        echo "Searching for values.yaml:"
        find . -maxdepth 5 -name "values.yaml" -print
        exit 1
      fi

      git config user.name "yasminemarzouk"
      git config user.email "marzouk.yasmine@esprit.tn"

      # Update tag under the chosen section in values.yaml
      sed -i "/^${helm_values_section_name}:/,/^[[:space:]]*tag:/s/^\([[:space:]]*tag:\).*/\1 ${helm_tag}/" "${VALUES_FILE}"

      git diff -- "${VALUES_FILE}" || true
      git add "${VALUES_FILE}"
      git commit -m "Release ${environment} ${docker_tag}" || echo "Nothing to commit"
      git push


# Kustomize Release
# - name: kustomize-release
#   image: k8s.gcr.io/kustomize/kustomize:v5.3.0
#   environment:
#     DEPLOYMENT_TOKEN:
#       from_secret: DEPLOYMENT_TOKEN
#   commands:
#     - export $(cat .outputs | xargs)
#     - git clone https://x-access-token:$DEPLOYMENT_TOKEN@github.com/$release_repo.git repo
#     - cd repo/$kustomize_folder
#     - git config user.name "yasminemarzouk"
#     - git config user.email "marzouk.yasmine@esprit.tn"
#     - kustomize edit set image $docker_tag
#     - git add .
#     - git commit -m "Release $environment $docker_tag"
#     - git push



