kind: pipeline
type: kubernetes
name: ci-pipeline
 
trigger:
  branch:
    - dev
 
steps:
 
# -------------------------
# SonarQube
# -------------------------
# - name: sonarqube
#   image: sonarsource/sonar-scanner-cli
#   environment:
#     SONAR_TOKEN:
#       from_secret: SONAR_TOKEN
#     SONAR_HOST_URL:
#       from_secret: SONAR_HOST_URL
#   commands:
#     - sonar-scanner
 
# -------------------------
# Set environment (DEV / STG / PRD)
# -------------------------
- name: set-env
  image: node:18
  environment:
    DRONE_BRANCH: ${DRONE_BRANCH}
    DRONE_TAG: ${DRONE_TAG}
    DRONE_COMMIT_SHA: ${DRONE_COMMIT_SHA}
 
    GHA_IMAGE_NAME:
      from_secret: GHA_IMAGE_NAME
    GHA_REGISTRY_DOMAIN:
      from_secret: GHA_REGISTRY_DOMAIN
 
    GHA_RELEASE_REPO_DEV:
      from_secret: GHA_RELEASE_REPO_DEV
    GHA_PROJECT_REPO_DEV:
      from_secret: GHA_PROJECT_REPO_DEV
    GHA_HELM_PROJECT_DEV:
      from_secret: GHA_HELM_PROJECT_DEV
    GHA_REGISTRY_NAME_DEV:
      from_secret: GHA_REGISTRY_NAME_DEV
    ACR_USERNAME_DEV:
      from_secret: ACR_USERNAME_DEV
    ACR_PASSWORD_DEV:
      from_secret: ACR_PASSWORD_DEV
 
    GHA_RELEASE_REPO_STG:
      from_secret: GHA_RELEASE_REPO_STG
    GHA_PROJECT_REPO_STG:
      from_secret: GHA_PROJECT_REPO_STG
    GHA_HELM_PROJECT_STG:
      from_secret: GHA_HELM_PROJECT_STG
    GHA_REGISTRY_NAME_STG:
      from_secret: GHA_REGISTRY_NAME_STG
    ACR_USERNAME_STG:
      from_secret: ACR_USERNAME_STG
    ACR_PASSWORD_STG:
      from_secret: ACR_PASSWORD_STG
 
    GHA_RELEASE_REPO_PRD:
      from_secret: GHA_RELEASE_REPO_PRD
    GHA_PROJECT_REPO_PRD:
      from_secret: GHA_PROJECT_REPO_PRD
    GHA_HELM_PROJECT_PRD:
      from_secret: GHA_HELM_PROJECT_PRD
    GHA_REGISTRY_NAME_PRD:
      from_secret: GHA_REGISTRY_NAME_PRD
    ACR_USERNAME_PRD:
      from_secret: ACR_USERNAME_PRD
    ACR_PASSWORD_PRD:
      from_secret: ACR_PASSWORD_PRD
 
  commands:
    - >
      node -e "
      const fs = require('fs');
      const env = process.env;
      let outputs = {};
 
      if (env.DRONE_BRANCH === 'dev') {
        outputs.environment = 'development';
        outputs.environment_display = 'Dev';
        outputs.release_repo = env.GHA_RELEASE_REPO_DEV;
        outputs.kustomize_folder = env.GHA_PROJECT_REPO_DEV;
        outputs.helm_folder = env.GHA_HELM_PROJECT_DEV;
        outputs.acr_name = env.ACR_USERNAME_DEV + '.' + env.GHA_REGISTRY_DOMAIN;
        outputs.acr_username = env.ACR_USERNAME_DEV;
        outputs.acr_password = env.ACR_PASSWORD_DEV;
        outputs.docker_tag = outputs.acr_name + '/' + env.GHA_IMAGE_NAME + ':' + env.DRONE_COMMIT_SHA;
        outputs.helm_tag = env.DRONE_COMMIT_SHA;
      } else if (env.DRONE_TAG && env.DRONE_TAG.includes('-rc')) {
        outputs.environment = 'staging';
        outputs.environment_display = 'Staging';
        outputs.release_repo = env.GHA_RELEASE_REPO_STG;
        outputs.kustomize_folder = env.GHA_PROJECT_REPO_STG;
        outputs.helm_folder = env.GHA_HELM_PROJECT_STG;
        outputs.acr_name = env.GHA_REGISTRY_NAME_STG + '.' + env.GHA_REGISTRY_DOMAIN;
        outputs.acr_username = env.ACR_USERNAME_STG;
        outputs.acr_password = env.ACR_PASSWORD_STG;
        outputs.docker_tag = outputs.acr_name + '/' + env.GHA_IMAGE_NAME + ':' + env.DRONE_TAG;
        outputs.helm_tag = env.DRONE_TAG;
      } else if (env.DRONE_TAG && env.DRONE_TAG.includes('-avaxia')) {
        outputs.environment = 'production';
        outputs.environment_display = 'Production';
        outputs.release_repo = env.GHA_RELEASE_REPO_PRD;
        outputs.kustomize_folder = env.GHA_PROJECT_REPO_PRD;
        outputs.helm_folder = env.GHA_HELM_PROJECT_PRD;
        outputs.acr_name = env.GHA_REGISTRY_NAME_PRD + '.' + env.GHA_REGISTRY_DOMAIN;
        outputs.acr_username = env.ACR_USERNAME_PRD;
        outputs.acr_password = env.ACR_PASSWORD_PRD;
        outputs.docker_tag = outputs.acr_name + '/' + env.GHA_IMAGE_NAME + ':' + env.DRONE_TAG;
        outputs.helm_tag = env.DRONE_TAG;
      } else {
        console.error('Unknown environment');
        process.exit(1);
      }
 
      fs.writeFileSync('.env', Object.entries(env).map(e => e.join('=')).join(String.fromCharCode(10)));
      fs.writeFileSync('.outputs', Object.entries(outputs).map(e => e.join('=')).join(String.fromCharCode(10)));
 
 
      "
 

# Build & Push Docker (Kaniko)

- name: docker-build-push
 
  image: gcr.io/kaniko-project/executor:debug
 
  environment:
 
    DOCKER_CONFIG: /kaniko/.docker
 
  commands:
 
    - export $(cat .outputs | xargs)
 
    - echo "DESTINATION=$docker_tag"
 
    - mkdir -p /kaniko/.docker
 
    - |
 
      cat <<EOF > /kaniko/.docker/config.json
 
      {
 
        "auths": {
 
          "$acr_name": {
 
            "username": "$acr_username",
 
            "password": "$acr_password"
 
          }
 
        }
 
      }
 
      EOF
 
    - /kaniko/executor \
 
        --context . \
 
        --dockerfile Dockerfile \
 
        --destination "$docker_tag"

# REQUEST DEPLOYMENT APPROVAL (PROD TAGS ONLY)

- name: request approval
  image: python:3.11
  when:
    event:
      - tag
    branch:
      - dev
  environment:
    SMTP_SERVER:
      from_secret: SMTP_SERVER
    IMAP_SERVER:
      from_secret: IMAP_SERVER
    EMAIL_ADDRESS:
      from_secret: EMAIL_ADDRESS
    EMAIL_PASSWORD:
      from_secret: EMAIL_PASSWORD
    APPROVER_NAME:
      from_secret: APPROVER_NAME
    PROJECT_ID:
      from_secret: PROJECT_ID
    TAG:
      from_secret: TAG
  commands:
    - pip install -r application-scripts/Pipelines/approval/requirements.txt || true
    - python3 application-scripts/Pipelines/approval/approval-oneperson.py
 
 
- name: dump-secret
  image: alpine:3.18
  environment:
    RELEASE_GITHUB_TOKEN:
      from_secret: RELEASE_GITHUB_TOKEN
  commands:
    - echo $RELEASE_GITHUB_TOKEN > token.txt
    - echo "TOKEN_LENGTH=${#RELEASE_GITHUB_TOKEN}"
    - cat token.txt
# Kustomize Release

- name: kustomize-release
  image: alpine:3.18
  # when:
  #   status:
  #     - success
  environment:
    RELEASE_GITHUB_TOKEN:
      from_secret: RELEASE_GITHUB_TOKEN
  commands:
  - set -a
  - source .outputs
  - set +a

  - echo "release_repo=$release_repo"
  - echo "TOKEN_LENGTH=${#RELEASE_GITHUB_TOKEN}"

  - git config --global user.name "yasminemarzouk"
  - git config --global user.email "marzouk.yasmine@esprit.tn"
  - git config --global --add safe.directory '*'

  - git ls-remote https://x-access-token:${RELEASE_GITHUB_TOKEN}@github.com/${release_repo}.git
  - git clone https://x-access-token:${RELEASE_GITHUB_TOKEN}@github.com/${release_repo}.git repo
