kind: pipeline
type: kubernetes
name: ci-pipeline

trigger:
  branch:
    - dev
  # event:
  #   - push
  #   - tag

steps:
  # -------------------------
  # SonarQube
  # -------------------------
  - name: sonarqube
    image: sonarsource/sonar-scanner-cli
    environment:
      SONAR_TOKEN:
        from_secret: SONAR_TOKEN
      SONAR_HOST_URL:
        from_secret: SONAR_HOST_URL
    commands:
      - sonar-scanner

  # -------------------------
  # Set environment (DEV / STG / PRD)
  # -------------------------
  - name: set-env
    image: node:18
    environment:
      DRONE_BRANCH: ${DRONE_BRANCH}
      DRONE_TAG: ${DRONE_TAG}
      DRONE_COMMIT_SHA: ${DRONE_COMMIT_SHA}

      # GLOBAL SECRETS
      GHA_HELM_VALUES_SECTION_NAME:
        from_secret: GHA_HELM_VALUES_SECTION_NAME
      GHA_IMAGE_NAME:
        from_secret: GHA_IMAGE_NAME
      GHA_REGISTRY_DOMAIN:
        from_secret: GHA_REGISTRY_DOMAIN

      # DEV
      GHA_RELEASE_REPO_DEV:
        from_secret: GHA_RELEASE_REPO_DEV
      GHA_PROJECT_REPO_DEV:
        from_secret: GHA_PROJECT_REPO_DEV
      GHA_HELM_PROJECT_DEV:
        from_secret: GHA_HELM_PROJECT_DEV
      GHA_REGISTRY_NAME_DEV:
        from_secret: GHA_REGISTRY_NAME_DEV
      ACR_USERNAME_DEV:
        from_secret: ACR_USERNAME_DEV
      ACR_PASSWORD_DEV:
        from_secret: ACR_PASSWORD_DEV

      # STG
      GHA_RELEASE_REPO_STG:
        from_secret: GHA_RELEASE_REPO_STG
      GHA_PROJECT_REPO_STG:
        from_secret: GHA_PROJECT_REPO_STG
      GHA_HELM_PROJECT_STG:
        from_secret: GHA_HELM_PROJECT_STG
      GHA_REGISTRY_NAME_STG:
        from_secret: GHA_REGISTRY_NAME_STG
      ACR_USERNAME_STG:
        from_secret: ACR_USERNAME_STG
      ACR_PASSWORD_STG:
        from_secret: ACR_PASSWORD_STG

      # PRD
      GHA_RELEASE_REPO_PRD:
        from_secret: GHA_RELEASE_REPO_PRD
      GHA_PROJECT_REPO_PRD:
        from_secret: GHA_PROJECT_REPO_PRD
      GHA_HELM_PROJECT_PRD:
        from_secret: GHA_HELM_PROJECT_PRD
      GHA_REGISTRY_NAME_PRD:
        from_secret: GHA_REGISTRY_NAME_PRD
      ACR_USERNAME_PRD:
        from_secret: ACR_USERNAME_PRD
      ACR_PASSWORD_PRD:
        from_secret: ACR_PASSWORD_PRD

    commands:
      - |
        node <<'EOF'
        const fs = require('fs')

        let env = {}
        let outputs = {}

        if (process.env.DRONE_BRANCH === 'dev') {
          outputs.environment = 'development'
          outputs.environment_display = 'Dev'
          outputs.release_repo = process.env.GHA_RELEASE_REPO_DEV
          outputs.kustomize_folder = process.env.GHA_PROJECT_REPO_DEV
          outputs.helm_folder = process.env.GHA_HELM_PROJECT_DEV
          outputs.acr_name = `${process.env.GHA_REGISTRY_NAME_DEV}.${process.env.GHA_REGISTRY_DOMAIN}`
          outputs.acr_username = process.env.ACR_USERNAME_DEV
          outputs.acr_password = process.env.ACR_PASSWORD_DEV
          outputs.docker_tag = `${outputs.acr_name}/${process.env.GHA_IMAGE_NAME}:${process.env.DRONE_COMMIT_SHA}`
          outputs.helm_tag = process.env.DRONE_COMMIT_SHA
        } else if (process.env.DRONE_TAG && process.env.DRONE_TAG.includes('-rc')) {
          outputs.environment = 'staging'
          outputs.environment_display = 'Staging'
          outputs.release_repo = process.env.GHA_RELEASE_REPO_STG
          outputs.kustomize_folder = process.env.GHA_PROJECT_REPO_STG
          outputs.helm_folder = process.env.GHA_HELM_PROJECT_STG
          outputs.acr_name = `${process.env.GHA_REGISTRY_NAME_STG}.${process.env.GHA_REGISTRY_DOMAIN}`
          outputs.acr_username = process.env.ACR_USERNAME_STG
          outputs.acr_password = process.env.ACR_PASSWORD_STG
          outputs.docker_tag = `${outputs.acr_name}/${process.env.GHA_IMAGE_NAME}:${process.env.DRONE_TAG}`
          outputs.helm_tag = process.env.DRONE_TAG
        } else if (process.env.DRONE_TAG && process.env.DRONE_TAG.includes('-avaxia')) {
          outputs.environment = 'production'
          outputs.environment_display = 'Production'
          outputs.release_repo = process.env.GHA_RELEASE_REPO_PRD
          outputs.kustomize_folder = process.env.GHA_PROJECT_REPO_PRD
          outputs.helm_folder = process.env.GHA_HELM_PROJECT_PRD
          outputs.acr_name = `${process.env.GHA_REGISTRY_NAME_PRD}.${process.env.GHA_REGISTRY_DOMAIN}`
          outputs.acr_username = process.env.ACR_USERNAME_PRD
          outputs.acr_password = process.env.ACR_PASSWORD_PRD
          outputs.docker_tag = `${outputs.acr_name}/${process.env.GHA_IMAGE_NAME}:${process.env.DRONE_TAG}`
          outputs.helm_tag = process.env.DRONE_TAG
        } else {
          console.error("Unexpected environment (not dev branch, not -rc tag, not -avaxia tag)")
          process.exit(1)
        }

        fs.writeFileSync('.env', Object.entries(env).map(e => e.join('=')).join('\n'))
        fs.writeFileSync('.outputs', Object.entries(outputs).map(e => e.join('=')).join('\n'))
        EOF

  # -------------------------
  # Build & Push Docker (Kaniko)
  # -------------------------
  - name: docker-build-push
    image: gcr.io/kaniko-project/executor:latest
    environment:
      DOCKER_CONFIG: /kaniko/.docker
    commands:
      - source .outputs
      - |
        cat <<EOF > /kaniko/.docker/config.json
        {
          "auths": {
            "$acr_name": {
              "username": "$acr_username",
              "password": "$acr_password"
            }
          }
        }
        EOF
      - >
        /kaniko/executor
        --context .
        --dockerfile Dockerfile
        --destination $docker_tag
        $(cat .env | sed 's/^/--build-arg /')

  # -------------------------
  # Kustomize Release
  # -------------------------
  - name: kustomize-release
    image: alpine/git
    commands:
      - source .outputs
      - git clone $release_repo repo
      - cd repo/$kustomize_folder
      - kustomize edit set image $docker_tag
      - git commit -am "Deploy $environment $docker_tag"
      - git push
